import ManiobrasTrenes._

val e1 = (List('A', 'B', 'C', 'D', 'E', 'F'), Nil, Nil)

val e2 = aplicarMovimiento(e1, Uno(3))
val e3 = aplicarMovimiento(e2, Dos(3))
val e4 = aplicarMovimiento(e3, Dos(-2))
val e5 = aplicarMovimiento(e4, Uno(-3))
val e6 = aplicarMovimiento(e5, Uno(15))
val e7 = aplicarMovimiento(e6, Uno(-100))
val e8 = aplicarMovimiento(e7, Dos(23))
val e9 = aplicarMovimiento(e8, Dos(-17))
val e10 = aplicarMovimiento(e9, Uno(6))
val e11 = aplicarMovimiento(e10, Uno(-6))
val e12 = aplicarMovimiento(e11, Uno(0))
val e13 = aplicarMovimiento(e12, Dos(0))

aplicarMovimientos(e1, List(Uno(2), Dos(3), Dos(-1), Uno(-2)))
aplicarMovimientos(e1, List(Uno(6), Uno(-6), Dos(6), Dos(-6)))
aplicarMovimientos(e1, List(Uno(10), Uno(-20), Dos(12), Dos(-17)))
aplicarMovimientos((List('X', 'Y', 'Z'), Nil, Nil), List(Uno(-2), Dos(1)))
aplicarMovimientos((List(5, 6, 7), Nil, Nil), List(Dos(-1), Uno(1)))
aplicarMovimientos((List(5, 6, 7), Nil, Nil), List(Uno(0), Dos(-50)))
aplicarMovimientos((List(5, 6, 7), List(5, 6, 7), List('X', 'Y', 'Z')), List(Uno(1), Dos(2)))
aplicarMovimientos((List('+', '-','*'), List(5, 6, 7), List('X', 'Y', 'Z')), List(Uno(1), Dos(3), Dos(-1)))

definirManiobra(List('A', 'B', 'C', 'D'), List('D', 'B', 'C', 'A'))
definirManiobra(List('x', 'y', 'z'), List('y', 'z', 'x'))
definirManiobra(List('a', 'b', 'c'), List('a', 'b', 'c'))
definirManiobra(List('+', '-', '*'), List('+', '*', '-'))
definirManiobra(List('A', 'B', 'C'), List('C', 'B', 'A'))
definirManiobra(List('A', 'B', 'A' ,'C'), List('A', 'A', 'B', 'C'))
definirManiobra(List(), List('A', 'A', 'B', 'C'))
definirManiobra(List(1,2,3), List(1,3,2))
definirManiobra(List(1,'a',2,'b'), List(2,'a',1,'b'))
